### ISSUE TITLE
EPIC: about translation

### ISSUE THREAD

**Issue by maxkoryukov** [VoleboNet/meta.dev#11]
Provide toolset for the i18n and l10n features.

## Main questions

- [x] how to store translations (locally)
  - [x] consider this: http://stackoverflow.com/a/26056292/1115187 (and [overall list](http://stackoverflow.com/a/10734119/1115187)
- [x] ext. service for translators -> **crowdin**
- integrations:
  - [x] ~ember-helper~ (obsolete)
  - [ ] l10n for handlebars (not sure)
  - [ ] l10n for nodejs
  - [ ] l10n for vuejs

## Services

Discover and test services
- [x]  :-1:  https://www.oneskyapp.com/
  - **no** few formats supported (no json for react-intl)
- [x] https://www.transifex.com/  **CURRENT CHOICE**
- [x] https://poeditor.com/pricing/
  - good for tiny and medium projects
  - main target - **PO** files, not the json.
  - **no** ICU support 
- [x]  :-1: https://lingohub.com/
  - **no** ICU support
  - **no** tricky UI (but better than phraseapp)
  - **no** help with pluralization
- [x]  :-1: https://phraseapp.com/
  
  After PO-editor, crowdin and transifex - phraseapp WebUI is not convenient(
  - **no** ICU
  - **no** UI
  - **no** help with pluralization
- [x]  :+1: https://crowdin.com/
  
  ICU :+1: 
  
  > We are already on the final stage of polishing the ICU support. We will support ICU-format for messages.
  > It should be available on production within a week or earlier.
  > You may also find useful this article. Here XLIFF file format is recommended for usage.
- [x] :-1: https://www.locize.io
  - **NO** collaboration tools
  - **YES** ICU support
  - **NO** pluralization helpers
  - UI - minimalism-guided, looks good
## Useful tools and links:
- :no_entry_sign: http://l10ns.org/ - tool for l10n-automation
- http://formatjs.io/guides/message-syntax/ - message format (how to store translations)
- http://docs.transifex.com/client/set/ - transifex tool
- **online ICU tester** http://format-message.github.io/icu-message-format-for-translators/editor.html
## Discussion about tools:
- messageformat/messageformat.js#69
- messageformat/messageformat.js/issues/55
- yahoo/intl-messageformat#106 - ICU management tools
## Other solutions:
- [ghost](https://github.com/TryGhost/Ghost/blob/master/core/server/i18n.js)
## Other related issues
- yahoo/react-intl#112 - Translation management

## Discussions in other projects

- https://github.com/TryGhost/Ghost/issues/5345 ([old](https://github.com/TryGhost/Ghost/issues/3801) ticket)

**Comment by maxkoryukov** [comment]
Transifex:

> Common name schema: `translations/<project_slug.resource_slug>/<lang>.<type>`

**Comment by maxkoryukov** [comment]
RIght now there is no service, that works with ICU messages and/or ICU-bundles (files with ICU messages).

Transifex doesn't allow to work with ICU, but it allows to translate JSON files.
On other hand, Transifex handles **pluralization** just for **XLIFF** and **PO-gettext** formats. Pluralization is not necessary right now, but in the future it could be very useful

So, current decision:
1. use Transifex with XLIFF.
2. on Build (gulp) create a JSON object with ICU messages from XLIFF file (there are several npm packages)

And remaining problems:

1 determine, how to format XLIFF with `plural` and `select` features (ICU stuff)
2 search for appropriate XLIFF -> JSON converter and appropriate HBS and Ember helpers (and nodejs lib) to get acceess to converted JSON
- ICU-bundle format description(`*.txt` files): http://source.icu-project.org/repos/icu/icuhtml/trunk/design/bnf_rb.txt
- ICU-message format: http://userguide.icu-project.org/formatparse/messages
- ICU tree (another one format): http://wiki.ecmascript.org/doku.php?id=globalization:messageformatting#modified_icu_approach
  NODEJS tools:

## NPM packages
- ICU-bundle to JSON: https://github.com/alex-dow/icu-converter
- Andy VanWagoner ICU tools  [format-message](https://www.npmjs.com/package/format-message). And underlying packages: [format-message-parse](https://www.npmjs.com/package/format-message-parse) and [format-message-interpret](https://www.npmjs.com/package/format-message-interpret).
- Yahoo ICU tools [off-site](http://formatjs.io/) and packages: [parser](https://www.npmjs.com/package/intl-messageformat-parser) and [formatter](https://www.npmjs.com/package/intl-messageformat)

### NON ICU
- [i18n-node](https://github.com/mashpie/i18n-node) by **mashpie**

**Comment by maxkoryukov** [comment]
Need to test:

* [ ] https://poeditor.com/pricing/
* [ ] https://lingohub.com/
* [ ]  https://phraseapp.com/
* [ ]  https://crowdin.com/
* [x]  :-1:  https://www.oneskyapp.com/
  > few formats supported (no json for react-intl)

**Comment by maxkoryukov** [comment]
format-message/format-message/issues/60

**Comment by maxkoryukov** [comment]
TryGhost/Ghost/issues/3801

**Comment by maxkoryukov** [comment]
## ISO8601 and custom formatting for dates in ICU

Bunch of issues, created in other repos, to find a easy way of custom formatting for date-variables:
- format-message/format-message#61
- yahoo/intl-messageformat#146
- messageformat/messageformat.js#162

Every issue about problem with custom format string for dates ([details on stackoverflow](http://stackoverflow.com/q/40230467/1115187))

**Comment by maxkoryukov** [comment]
There is one alive and beauty repository: https://github.com/messageformat/messageformat.js

I think, it is not a bad solution for the server-side translations (outside of HBS).

But! There is no neither HBS-helper nor Ember-package..

**Comment by maxkoryukov** [comment]
Watch this too: https://github.com/TryGhost/Ghost/issues/5345

**Comment by maxkoryukov** [comment]
Globalization!

http://rxaviers.github.io/javascript-globalization/

**Comment by jamuhl** [comment]
We now fully support icu format at https://locize.com (and plan to extend based on your feedback / demand):

- highlighting
- validation
- machine translations
- plural conversion between source and target language
- prettify of your icu strings

<img width="1152" alt="screen shot 2017-10-29 at 14 12 00" src="https://user-images.githubusercontent.com/977772/32144372-00e2726a-bcb8-11e7-838c-7f26fdb5587b.png">


Your feedback would be very welcome - also if someone could provide us with a file  extracted we could look into supporting that for importing (beside xliff, json, ...)

**Comment by maxkoryukov** [comment]
@jamuhl , thank you for a good advice;)

I tried to work with locize, but I ran into difficulties (mentioned in the first message). But it seems like new Locize dropped all cons))

Just give me some time for tests, our dev-resources are very limited...

**Comment by jamuhl** [comment]
@maxkoryukov awesome...no need to rush...would be awesome if you could provide us with feedback if something could be changes or added to make it perfect. Luckily were still at a point were we add features and could optimize the system. So if there is something wrong, or could be better or needed (additional format for import/export) let us know...

**Comment by maxkoryukov** [comment]
top 30 languages:

* Afrikaans
* Arabic
* Catalan
* Chinese Simplified
* Chinese Traditional
* Czech
* Danish
* Dutch
* English
* Finnish
* French
* German
* Greek
* Hebrew
* Hungarian
* Italian
* Japanese
* Korean
* Norwegian
* Polish
* Portuguese
* Portuguese, Brazilian
* Romanian
* Russian
* Serbian (Cyrillic)
* Spanish
* Swedish
* Turkish
* Ukrainian
* Vietnamese

**Comment by jamuhl** [comment]
@maxkoryukov hope you already got time to checkout locize new ICU support - feedback would be awesome and like said we would love to extend imports if there is some special message catalog we do not yet support...

**Comment by maxkoryukov** [comment]
@jamuhl, we are testing Locize on this week 

First results: our translators tried to use Locize, but we didn't even start to test ICU, because I18N-team found that UI is not convenient for work.

Moreover, they told me, that Locize doesn't support the translation for DOCX-files.

**Comment by jamuhl** [comment]
@maxkoryukov yes...we only offer translation of "technical" code projects. The UI does not offer options to translate docs, pdf, ... our focus is really to be strong on continuous localization of software projects not on translating manuals, ...

Would be great to hear what they did not like...guessing they come from a SDL trados world and not from software translation

**Comment by jamuhl** [comment]
beside to simplify react-intl integration there is now also https://github.com/maciejw/react-intl-namespaces

- enables multiple files
- enables incontext editing

**Comment by maxkoryukov** [comment]
@jamuhl maybe soon I'll publish the summary of their reviews;)
