### ISSUE TITLE
TOOLS: Self-documented code. Conventions

### ISSUE THREAD

**Issue by maxkoryukov** [VoleboNet/meta.dev#18]
* [ ] choose a lib and tool for JS code
* [ ] choose style (google vs. ???)
* [ ] embed autodoc into github pages

----

Ember doc sample: https://github.com/emberjs/ember.js/blob/v2.7.0/packages/ember-htmlbars/lib/keywords/get.js#L105
